# Generated by Django 4.2.8 on 2024-02-13 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='serials_images', verbose_name='Изображение')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='Рейтинг')),
                ('quantity_seasons', models.PositiveIntegerField(default=2, verbose_name='Количество сезонов')),
                ('release_year', models.PositiveIntegerField(default=1, verbose_name='Год выхода')),
                ('genre', models.ForeignKey(default='Выберите жанр', on_delete=django.db.models.deletion.SET_DEFAULT, to='serials.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Сериал',
                'verbose_name_plural': 'Сериалы',
            },
        ),
    ]
