# Generated by Django 4.2.8 on 2024-02-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0002_alter_genre_options_alter_genre_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='quantity_series',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество серий'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='quantity_seasons',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество сезонов'),
        ),
    ]
