# Generated by Django 4.2.8 on 2024-02-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0003_serial_quantity_series_alter_serial_quantity_seasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Рейтинг'),
        ),
    ]
